### ISSUE TITLE
Payum omnipay-bridge integraton

### ISSUE THREAD

**Issue by mcbuckets** [academe/OmniPay-Payone#14]
Hello, I'm struggling to find a way to implement this library with Payum and payum omnipay-bridge.

As far as i understand if this library works with omnipay then it will work with the bridge, too. But when using this configuration:

```
 payum:
    storages:
        App\PaymentBundle\Entity\Payment: { doctrine: orm }
    security:
        token_storage:
            App\PaymentBundle\Entity\PaymentToken: { doctrine: orm }
    gateways:
        payone_frontend_client:
            factory: omnipay
            type: Payone(lets's say)
            options:

```
i get the "Given omnipay gateway type Payone or class is not supported" and payone gateways are not listed among supported gateways.

```
Supported: AuthorizeNet_AIM, AuthorizeNet_SIM, Buckaroo_CreditCard, Buckaroo_Ideal, Buckaroo_PayPal, CardSave, Coinbase, Dummy,  
   Eway_Rapid, FirstData_Connect, GoCardless, Manual, Migs_ThreeParty, Migs_TwoParty, Mollie, MultiSafepay, Netaxept, NetBanx, PayFast, Payflow_Pro, PaymentExpress_PxPay, PaymentExpress_PxPo  
  st, PayPal_Express, PayPal_Pro, Pin, SagePay_Direct, SagePay_Server, SecurePay_DirectPost, Stripe, TargetPay_Directebanking, TargetPay_Ideal, TargetPay_Mrcash, WorldPay    
```      

Does anybody know if its possible to this kind of integration?
